### ISSUE TITLE
Rather spread behavior of overlap element as a function of Q

### ISSUE THREAD

**Issue by yuan-gist** [mturiansky/nonrad#4]
Hi, I am trying to compute `Wif` with `get_Wif_from_WSWQ`. However, I find that for some defect transitions the WSWQ element is not linear with Q, making it unlikely to use finite difference. I tested and find that this is not because of convergence (like cut off energy) or unreasonable displacements.

Could you please advice how to solve this issue? I wonder this may not be solved, rather it is due to the material itself.

**Comment by mturiansky** [comment]
Could you provide some more information? In principle, if you make a large enough displacement, things won't look linear anymore. It's a finite difference approximation, so you should only extract the matrix element from the region where it's closest to linear. On the other hand, if you make too small a displacement, your finite difference formula can be sensitive to noise, so using a slightly larger displacement can be more robust.

**Comment by yuan-gist** [comment]
Hi Mark, thanks for prompt reply. Due to a maintainance of our HPC yesterday, I can now come back to you.

Yes. I am aware of possible issues inherent in finite difference method, so I always check -50% to 50% displacement with 11 points, and -20% t0 20% displacement with 11 points, and -10% to 10% displacement with 11 points, in order to make issue the finite difference is not subject to numerical instability.

You can find a small result here: https://github.com/yuan-gist/nonrad_test/blob/main/D_q0_capture_h_-0.5_0.5_11_nupdown.ipynb

There, I try to calculate the overlap element between the defect band (index=1059) and three valence bands (1056, 1057, 1058). The defect band is quite deep in the band gap and associated with quite localized charge distribution.

**Comment by mturiansky** [comment]
The overlap between 1059 and 1056 looks fine to me; it's mostly linear, especially over a smaller range. Is your valence band maximum in fact triply degenerate? These "kinks" in the overlaps that you see may be due to orbitals changing ordering. Based on your indices, it seems like you may have many defect orbitals in the gap. Are you sure that the lower ones don't overlap with the band edge once you start displacing atoms?

A test you might try is to compute the overlap between say 1057 in the equilibrium geometry and 1057 in the displaced geometry. If they are in fact the same state, then the overlap should be close to 1. If the ordering changed, then the overlap will drop to close to 0.

**Comment by yuan-gist** [comment]
Hi Mark. Thanks a lot for the insights. Yes, I have many defect states in the gap, and some of them fall into the valence bands. Yet, I check the orbital character of the defect states and take care of valence/conduction bands. OK, I will do the test.
